Feature/direct message #23
Trapscendence/ft_transcendence pull request #48
Opened 2021-11-11 12:52 UTC by seohee-choi

DM 최소기능 구현

2021-11-13 04:09 UTC, moon9ua requested changes
백엔드 수정된거 반영하고 머지하도록 합시다! 화이팅

2021-11-13 13:59 UTC, evelon approved these changes
잘 보았습니다

2021-11-16 15:18 UTC, evelon commented
언제 합쳐야할까요.
제안: 플리퀘 날린 이후에는 수정 커밋 말고는 하지 말도록 합시다. 예를 들어서 풀리퀘 직전에 새로 브랜치를 파서 그 브랜치에서 리퀘를 날리는 방법이 있습니다.

2021-11-16 15:18 UTC, moon9ua commented
저희 모든 머지는 수요일에 하기로 한거 아니었나욤?

2021-11-16 15:19 UTC, evelon commented
이미 끝났어야할 풀리퀘를 너무 오래 끌고있는 거 같아서요. 다음에는 그렇게 하면 좋을 것 같습니다.

2021-11-17 08:06 UTC, evelon approved these changes
다 끝낚닦!!

2021-11-17 09:00 UTC, moon9ua approved these changes
일합(일단 합치자는 뜻)
수정은... 따로 브랜치 파서 하면 되지 않을까..!!!

2021-11-17 09:03 UTC, SeheonYu approved these changes
Good!

2021-11-17 09:04 UTC, merged